// Code generated by protoc-gen-go. DO NOT EDIT.
// source: saleresp.proto

package sale

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CMIXText struct {
	Text                 string              `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Reply                *TextReply          `protobuf:"bytes,2,opt,name=reply,proto3" json:"reply,omitempty"`
	Preview              *TextNetworkPreview `protobuf:"bytes,3,opt,name=preview,proto3" json:"preview,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *CMIXText) Reset()         { *m = CMIXText{} }
func (m *CMIXText) String() string { return proto.CompactTextString(m) }
func (*CMIXText) ProtoMessage()    {}
func (*CMIXText) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ed91c35286e752d, []int{0}
}

func (m *CMIXText) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMIXText.Unmarshal(m, b)
}
func (m *CMIXText) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMIXText.Marshal(b, m, deterministic)
}
func (m *CMIXText) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMIXText.Merge(m, src)
}
func (m *CMIXText) XXX_Size() int {
	return xxx_messageInfo_CMIXText.Size(m)
}
func (m *CMIXText) XXX_DiscardUnknown() {
	xxx_messageInfo_CMIXText.DiscardUnknown(m)
}

var xxx_messageInfo_CMIXText proto.InternalMessageInfo

func (m *CMIXText) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *CMIXText) GetReply() *TextReply {
	if m != nil {
		return m.Reply
	}
	return nil
}

func (m *CMIXText) GetPreview() *TextNetworkPreview {
	if m != nil {
		return m.Preview
	}
	return nil
}

type TextNetworkPreview struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Image                []byte   `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TextNetworkPreview) Reset()         { *m = TextNetworkPreview{} }
func (m *TextNetworkPreview) String() string { return proto.CompactTextString(m) }
func (*TextNetworkPreview) ProtoMessage()    {}
func (*TextNetworkPreview) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ed91c35286e752d, []int{1}
}

func (m *TextNetworkPreview) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TextNetworkPreview.Unmarshal(m, b)
}
func (m *TextNetworkPreview) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TextNetworkPreview.Marshal(b, m, deterministic)
}
func (m *TextNetworkPreview) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TextNetworkPreview.Merge(m, src)
}
func (m *TextNetworkPreview) XXX_Size() int {
	return xxx_messageInfo_TextNetworkPreview.Size(m)
}
func (m *TextNetworkPreview) XXX_DiscardUnknown() {
	xxx_messageInfo_TextNetworkPreview.DiscardUnknown(m)
}

var xxx_messageInfo_TextNetworkPreview proto.InternalMessageInfo

func (m *TextNetworkPreview) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *TextNetworkPreview) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *TextNetworkPreview) GetImage() []byte {
	if m != nil {
		return m.Image
	}
	return nil
}

type TextReply struct {
	Message              string              `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	SenderId             []byte              `protobuf:"bytes,2,opt,name=senderId,proto3" json:"senderId,omitempty"`
	UniqueId             []byte              `protobuf:"bytes,3,opt,name=uniqueId,proto3" json:"uniqueId,omitempty"`
	Preview              *TextNetworkPreview `protobuf:"bytes,4,opt,name=preview,proto3" json:"preview,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *TextReply) Reset()         { *m = TextReply{} }
func (m *TextReply) String() string { return proto.CompactTextString(m) }
func (*TextReply) ProtoMessage()    {}
func (*TextReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ed91c35286e752d, []int{2}
}

func (m *TextReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TextReply.Unmarshal(m, b)
}
func (m *TextReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TextReply.Marshal(b, m, deterministic)
}
func (m *TextReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TextReply.Merge(m, src)
}
func (m *TextReply) XXX_Size() int {
	return xxx_messageInfo_TextReply.Size(m)
}
func (m *TextReply) XXX_DiscardUnknown() {
	xxx_messageInfo_TextReply.DiscardUnknown(m)
}

var xxx_messageInfo_TextReply proto.InternalMessageInfo

func (m *TextReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *TextReply) GetSenderId() []byte {
	if m != nil {
		return m.SenderId
	}
	return nil
}

func (m *TextReply) GetUniqueId() []byte {
	if m != nil {
		return m.UniqueId
	}
	return nil
}

func (m *TextReply) GetPreview() *TextNetworkPreview {
	if m != nil {
		return m.Preview
	}
	return nil
}

func init() {
	proto.RegisterType((*CMIXText)(nil), "sale.CMIXText")
	proto.RegisterType((*TextNetworkPreview)(nil), "sale.TextNetworkPreview")
	proto.RegisterType((*TextReply)(nil), "sale.TextReply")
}

func init() {
	proto.RegisterFile("saleresp.proto", fileDescriptor_8ed91c35286e752d)
}

var fileDescriptor_8ed91c35286e752d = []byte{
	// 243 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x90, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0xd9, 0x36, 0xb5, 0xcd, 0x58, 0x54, 0x06, 0x0f, 0x8b, 0xa7, 0x12, 0x10, 0x7a, 0xca,
	0xa1, 0xfe, 0x03, 0x3d, 0xe5, 0xa0, 0x94, 0xc1, 0x83, 0xd7, 0x4a, 0x06, 0x09, 0x6e, 0x9b, 0x75,
	0x77, 0x63, 0xdb, 0x9f, 0xe1, 0x3f, 0x96, 0xd9, 0x6d, 0xa2, 0xe0, 0xc5, 0xdb, 0x7c, 0xf3, 0x5e,
	0x5e, 0xde, 0x2c, 0x5c, 0xf8, 0x8d, 0x61, 0xc7, 0xde, 0x96, 0xd6, 0xb5, 0xa1, 0xc5, 0x4c, 0xb8,
	0x38, 0xc2, 0xec, 0xe1, 0xb1, 0x7a, 0x79, 0xe6, 0x43, 0x40, 0x84, 0x2c, 0xf0, 0x21, 0x68, 0xb5,
	0x50, 0xcb, 0x9c, 0xe2, 0x8c, 0xb7, 0x30, 0x71, 0x6c, 0xcd, 0x51, 0x8f, 0x16, 0x6a, 0x79, 0xbe,
	0xba, 0x2c, 0xe5, 0xab, 0x52, 0xec, 0x24, 0x6b, 0x4a, 0x2a, 0xae, 0x60, 0x6a, 0x1d, 0x7f, 0x36,
	0xbc, 0xd7, 0xe3, 0x68, 0xd4, 0x3f, 0xc6, 0x27, 0x0e, 0xfb, 0xd6, 0xbd, 0xaf, 0x93, 0x4e, 0xbd,
	0xb1, 0x20, 0xc0, 0xbf, 0x32, 0x5e, 0xc1, 0xb8, 0x73, 0xe6, 0xd4, 0x41, 0x46, 0xbc, 0x86, 0x49,
	0x68, 0x82, 0xe1, 0x58, 0x21, 0xa7, 0x04, 0xb2, 0x6d, 0xb6, 0x9b, 0x37, 0x8e, 0xff, 0x9b, 0x53,
	0x82, 0xe2, 0x4b, 0x41, 0x3e, 0x94, 0x43, 0x0d, 0xd3, 0x2d, 0x7b, 0x2f, 0xae, 0x94, 0xd7, 0x23,
	0xde, 0xc0, 0xcc, 0xf3, 0xae, 0x66, 0x57, 0xd5, 0x31, 0x76, 0x4e, 0x03, 0x8b, 0xd6, 0xed, 0x9a,
	0x8f, 0x8e, 0xab, 0xfa, 0x14, 0x3e, 0xf0, 0xef, 0x3b, 0xb3, 0x7f, 0xde, 0x79, 0x3f, 0x5a, 0xab,
	0xd7, 0xb3, 0xf8, 0xe6, 0x77, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x44, 0x3e, 0x8b, 0x20, 0x85,
	0x01, 0x00, 0x00,
}
